returne override and add mysql-client on pre:

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -35,4 +35,21 @@ test:
         else
           echo "Setup Test passed"
           exit 0 
+        fi        
+    - docker-compose -f docker-compose.yml run phpfpm /bin/sh -c "apk add --no-cache mysql-client
+
+  override:
+    - |
+        docker-compose -f docker-compose.yml \ 
+              run phpfpm /bin/sh -c "php -d memory_limit=2G /src/www/bin/magento dev:tests:run integration --ansi --no-interaction" | tee IntegrationTest
+      
+        if grep -q "F" IntegrationTest
+        then
+          echo "Setup Test Failed:"
+          cat ./IntegrationTest | grep fail | awk '{print $2, $3}'
+        exit 1
+
+        else
+          echo "Setup Test passed"
+          exit 0 
         fi
